### ISSUE TITLE
preroute callback leaves orphaned components in tree

### ISSUE THREAD

**Issue by damir** [nolimits4web/Framework7-Vue#12]
Same is when using router methods directly.

How do you get router from vue instance anyway? I patched  view.vue onF7Init method by adding this on the bottom to be able to use it:

`this.$root.router = self.f7View.router`

Thank you!

**Comment by nolimits4web** [comment]
Yes, there is a but in Vue compilier, page should be removed from tree, it uses pageBeforeRemove callback but during compilation it changes it to lowercase pagebeforeremove so it doesn't work like expected

As for router I'll also add it. It is a bit wrong to to assign it to root because you may have several views/router in single app

**Comment by damir** [comment]
I made two pages linked to each other, each click is generating a new instance and back link is removing them from the tree in reverse. I guess the history is built this way but duplicate pages should be removed for this kind of loop.

Removing previous page using reload option did the job for redirects as I don't have a deep tree. 

Thank you.
