### ISSUE TITLE
Material Support

### ISSUE THREAD

**Issue by bencompton** [nolimits4web/Framework7-Vue#98]
Is Material support considered to be a well-tested path in Framework7 Vue at this point? 

I haven't spent a lot of time working with Material myself in Framework7 Vue, but when I switch the kitchen sink or webpack template over to use Material (by setting `material: true` and using Material CSS), I notice that mainly that the navbars don't look correct (the navbar text sits on top of the back buttons). In the webpack template where the view has `navbar-fixed` set, the first page navbar hides subsequent page navbars.

Am I doing something incorrectly, is it supposed to be up to the consumer to manage differences in iOS and Material like that, or is that just a bug?

**Comment by nolimits4web** [comment]
@bencompton, yes, it is well supported. Just added commits to fix navbar's behavior. Because we have dynamic navbar in iOS theme it should be placed in different place (it is explained in docs [here](http://framework7.io/vue/app-layout.html#advanced-layout)), just forgot to use same in demo apps and templates. Fixed now. It is handled automatically by router on page/component load but on initial state. This is also can be automated by kind of hack which is not yet documented as i don't really like how it works internally at the moment, but it can be used in this way:
```html
<!-- make empty view -->
<f7-view :init="true" url="/" :dynamic-navbar="true"></f7-view>
```
```js
//in routes
...
{
  path: '/',
  component: IndexPageComponent
}
...

**Comment by bencompton** [comment]
@nolimits4web - thanks for the explanation! Guess I must've overlooked that in the docs. I'll get the React examples updated accordingly.
